### ISSUE TITLE
omegaconf.errors.ConfigAttributeError: Missing key datafiles

### ISSUE THREAD

**Issue by swcrazyfan** [Lightning-AI/lightning-transformers#236]
## 🐛 Bug

I follow everything in the documentary precisely on Kaggle, Colab, and a TPU VM, but it always give me a missing key datafiles error.

### To Reproduce

Run this Kaggle notebook. Then, see the final output.

[](https://www.kaggle.com/swcrazyfan/lightning-transformers-test)

This is the error I get, but you can read the full thing in the notebook:

[](https://www.kaggle.com/swcrazyfan/lightning-transformers-test)
```
Error executing job with overrides: ['dataset.cfg.train_file=../input/netkjvsourcetarget/train.json', 'dataset.cfg.validation_file=../input/netkjvsourcetarget/eval.json', 'task=nlp/summarization', 'trainer.gpus=1']
Traceback (most recent call last):
  File "train.py", line 10, in hydra_entry
    main(cfg)
  File "/kaggle/working/lightning-transformers/lightning_transformers/cli/train.py", line 77, in main
    logger=logger,
  File "/kaggle/working/lightning-transformers/lightning_transformers/cli/train.py", line 52, in run
    data_module.setup("fit")
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/core/datamodule.py", line 474, in wrapped_fn
    fn(*args, **kwargs)
  File "/kaggle/working/lightning-transformers/lightning_transformers/core/nlp/data.py", line 31, in setup
    dataset = self.load_dataset()
  File "/kaggle/working/lightning-transformers/lightning_transformers/core/nlp/data.py", line 62, in load_dataset
    elif self.cfg.datafiles:
omegaconf.errors.ConfigAttributeError: Missing key datafiles
    full_key: datafiles
    object_type=dict
```
Set the environment variable `HYDRA_FULL_ERROR=1` for a complete stack trace.

**Comment by swcrazyfan** [comment]
Can anyone point me in the right direction?

**Comment by SeanNaren** [comment]
We're moving away from Hydra configs existing in this repo, and all examples are now pure Pytorch Lightning. Let me know if there are any issues with this and I can help get around this!
